version: '3'

services:
  node:
    build: .
    container_name: talker-manager
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
volumes:
  data:
    driver: local
